### ISSUE TITLE
how i filter by name?

### ISSUE THREAD

**Issue by dani3lod** [lukemurray/EntityGraphQL#51]
hi, i try implement the example of the documentation, only works filter by id.

Query:
{
    property(name: "daniel") {
      name id
    }
}

Results:
{
    "errors": [
        {
            "message": "No argument 'name' found on field 'property'"
        }
    ],
    "data": {}
}

property contains:
    public class Property
    {
        public uint Id { get; set; }
        public string Name { get; set; }
        public PropertyType Type { get; set; }
        public Location Location { get; set; }
    }

**Comment by lukemurray** [comment]
Hi, when you start your schema with `SchemaBuilder.FromObject<T>()` this only generates fields for properties in that object graph. The only "smart" thing it tries is to add an extra field for any root level property that is of type `IEnumerable<T>` where `T` has a property name `Id`. The extra field is a field that takes an `id` argument.

It does not generate arguments or fields for every property on type `T`. Partly because it doesn't know your data. You could have a unique key on `Name` and want it to return a single item. Or you might want it to search.

Hopefully that explains it. [Here](https://github.com/lukemurray/EntityGraphQL#customizing-the-schema) very briefly explains how to add other fields. I do need to expand that section.

Short answer, you need to change the `property` field. Assuming you have a context like this

```c#
public class MyContext
{
    public List<Property> Properties { get; set; }
}
public class Property
{
    public uint Id { get; set; }
    public string Name { get; set; }
    public PropertyType Type { get; set; }
    public Location Location { get; set; }
}
```

If you use `SchemaBuilder.FromObject<MyContext>()` it will generate *2* fields at the root.

```gql
{
    # field auto generated - return a list of properties
    properties { id name }
    # field auto generated - return a single property by ID
    property(id: 3232) { name id }
}
```

I assume you want to search by name so you want to replace the `properties` field, not the `property` field you use in your comment.

```c#
var schema = SchemaBuilder.FromObject<MyContext>();
// replace properties field with one that takes an optional name argument
schema.ReplaceField("properties", new { name = (string)null }, (ctx, args) => ctx.Properties.WhereWhen(p => p.Name.ToLower().Contains(args.name), !string.IsNullOrEmpty(args.name)), "Return a list of properties optional filtered by name");
```

You can change `ctx.Properties.WhereWhen(p => p.Name.ToLower().Contains(args.name), !string.IsNullOrEmpty(args.name))` to whatever logic you need to filter/search.

Hope that helps.

**Comment by lukemurray** [comment]
I also updated the readme with the example above.
